export const data = {
  Travel: [
    {
      id: 1,
      name: 'Create Luxury itinerary ',
      nameBreak: '4 nights in New York',
      category: 'LUXURY',
      image: '/assets/images/earnTravelCredit/luxury.png',
    },
    {
      id: 2,
      name: 'Create Budget itinerary',
      nameBreak: '4 nights in New York',
      category: 'BUDGET',
      image: '/assets/images/earnTravelCredit/budget.png',
    },
    {
      id: 3,
      name: 'Create Adventure itinerary',
      nameBreak: '4 nights in New York',
      category: 'ADVENTURE',
      image: '/assets/images/earnTravelCredit/adventure.png',
    },
    {
      id: 4,
      name: 'Create Romantic itinerary',
      nameBreak: '4 nights in New York',
      category: 'ROMANTIC',
      image: '/assets/images/earnTravelCredit/romantic.png',
    },
    {
      id: 5,
      name: 'Create Cultural itinerary',
      nameBreak: '4 nights in New York',
      category: 'CULTURAL',
      image: '/assets/images/earnTravelCredit/culture.png',
    },
    {
      id: 6,
      name: 'Create Foodies itinerary',
      nameBreak: '4 nights in New York',
      category: 'FOODIES',
      image: '/assets/images/earnTravelCredit/food.png',
    },
    {
      id: 7,
      name: 'Create Wellness itinerary',
      nameBreak: '4 nights in New York',
      category: 'WELLNESS',
      image: '/assets/images/earnTravelCredit/wellness.png',
    },
    {
      id: 8,
      name: 'Create Family itinerary',
      nameBreak: '4 nights in New York',
      category: 'FAMILY',
      image: '/assets/images/earnTravelCredit/family.png',
    },
    {
      id: 9,
      name: 'Create Solo itinerary',
      nameBreak: '4 nights in New York',
      category: 'SOLO',
      image: '/assets/images/earnTravelCredit/solo.png',
    },
    {
      id: 10,
      name: 'Create Digital nomads itinerary',
      nameBreak: '4 nights in New York',
      category: 'DIGITAL_NOMADS',
      image: '/assets/images/earnTravelCredit/digital.png',
    },
    {
      id: 11,
      name: 'Create Business travellers itinerary',
      nameBreak: '4 nights in New York',
      category: 'BUSINESS_TRAVELERS',
      image: '/assets/images/earnTravelCredit/digital.png',
    },
  ],
};
